### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Gorbanev9999** [Source2ZE/AcceleratorCS2#2] opened 2024-05-14 12:59 UTC
After the cs2 update in May, everyone started to crash)

**Comment by Vauff** [comment] 2024-10-06 23:44
Just going to close this, due to not being able to reproduce, the vague report, and time passed. If you're still experiencing issues with the latest release, also make sure you're not running CounterStrikeSharp with uncaught exceptions.

**Closed as not planned by Vauff** 2024-10-06 23:44 UTC
